name: Update Readme and Assets on WP.org
on:
  push:
    branches:
      - main
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'
  workflow_dispatch:

jobs:
  update-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: kurl-short-url-manager-yourls
        IGNORE_OTHER_FILES: true
